### PR TITLE
Fix invoke and attach

### LINKED ISSUE #23: Invoking an action after having attached the debugger fails
```
(wskdb) attach hello
Attaching to hello
   Creating action trampoline
ok
(wskdb) invoke hello
Debug session requested
TypeError: "options" must be a string or an object, got number instead.
    at getOptions (fs.js:51:11)
    at Object.fs.writeFile (fs.js:1193:13)
    at onTempDirCreation (/Users/andreas/Downloads/openwhisk-debugger-master/client/lib/debug-nodejs.js:78:9)
    at _dirCreated (/Users/andreas/Downloads/openwhisk-debugger-master/client/node_modules/tmp/lib/tmp.js:310:7)
    at FSReqWrap.oncomplete (fs.js:112:15)
TypeError: "options" must be a string or an object, got number instead.
    at getOptions (fs.js:51:11)
    at Object.fs.writeFile (fs.js:1193:13)
    at onTempDirCreation (/Users/andreas/Downloads/openwhisk-debugger-master/client/lib/debug-nodejs.js:78:9)
    at _dirCreated (/Users/andreas/Downloads/openwhisk-debugger-master/client/node_modules/tmp/lib/tmp.js:310:7)
    at FSReqWrap.oncomplete (fs.js:112:15)

```

### LINKED ISSUE #24: Invoke <action> just hangs
I have a very simple hello world action. I can attach to it, but nothing happens when I try to invoke it:

> Scotts-MacBook-Pro:openwisk scottchapman$ wskdb MyTest
> Welcome to the OpenWhisk Debugger
> 
> Attaching to MyTest
>    Creating action trampoline
> ok
> (wskdb) invoke MyTest
>

### PR DESCRIPTION
**Pull request by starpit**
update to the latest OpenWhisk way of fetching auth key, namespace, and to use ":default" suffix for all action kinds

fixes #23
fixes #24

### CODE REVIEW

File: client/lib/activations.js [hunk 1]
```diff
@@ -44,7 +43,7 @@ exports.waitForActivationCompletion = function waitForActivationCompletion(wskpr
 	    // scan the recent activations, looking for the
 	    // anticipated activation by invoked-entity name
 	    //
-	    ow.activations.list({ limit: 1, name: waitForThisAction, since: since, docs: true }).then(list => {
+	    ow.activations.list({ limit: 1, name: waitForThisAction, xsince: since, docs: true }).then(list => {
```
Comment (rabbah) [inline client/lib/activations.js]: xsince?
